Fix theme selection on onboarding
Infomaniak/ios-mail pull request #358
Opened 2022-10-13 11:15 UTC by Ambrdctr

2022-10-13 13:06 UTC, PhilippeWeidmann approved these changes

2022-10-13 13:16 UTC, PhilippeWeidmann requested changes

2022-10-13 13:16 UTC, PhilippeWeidmann commented on Mail/Views/Onboarding/OnboardingView.swift
> +                    SlideView(slide: slide)
Background image is missing. Geometry reader doens't work in SlideView

2022-10-13 13:16 UTC, PhilippeWeidmann commented on Mail/Views/Onboarding/OnboardingView.swift
> +    var isScrollEnabled: Bool
Make properties private

2022-10-18 12:20 UTC, PhilippeWeidmann approved these changes

2022-10-18 12:24 UTC, Lnamw approved these changes

2022-10-18 12:24 UTC, merged