Mail view
Infomaniak/ios-mail pull request #39
Opened 2022-04-11 07:15 UTC by Ambrdctr

2022-04-12 15:15 UTC, flowbe requested changes
Small changes needed on comments, formatters, and `getAttachementsSize`

2022-04-13 07:35 UTC, flowbe approved these changes

2022-04-13 09:04 UTC, flowbe approved these changes

2022-04-13 09:12 UTC, valentinperignon submitted a review, later dismissed

2022-04-13 09:28 UTC, valentinperignon approved these changes

2022-04-13 09:33 UTC, Lnamw approved these changes

2022-04-13 09:34 UTC, merged