Routes thread
Infomaniak/ios-mail pull request #401
Opened 2022-11-25 12:34 UTC by Ambrdctr

2022-11-28 12:53 UTC, PhilippeWeidmann requested changes

2022-11-28 12:53 UTC, PhilippeWeidmann commented on MailCore/Cache/MailboxManager.swift
> +                                        value.messageIds.detached().contains { message.linkedUids.detached().contains($0) }
It looks like detached() is not needed here

2022-11-29 11:58 UTC, valentinperignon approved these changes

2022-11-29 13:20 UTC, valentinperignon approved these changes

2022-11-29 14:02 UTC, valentinperignon approved these changes

2022-11-29 14:03 UTC, merged